set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin() "Plugins go between begin and end
Plugin 'VundleVim/Vundle.vim'
Plugin 'reedes/vim-pencil'
Plugin 'preservim/nerdtree'
Plugin 'vim-airline/vim-airline'
Plugin 'tpope/vim-commentary'
Plugin 'pangloss/vim-javascript'
Plugin 'prettier/vim-prettier'
call vundle#end()
filetype plugin indent on
syntax on
set rnu
set nu
set clipboard+=unnamedplus
set hidden
set tabstop=4
set shiftwidth=4
set expandtab
set nowrap
set sidescroll=1
nnoremap <C-n> :NERDTree <bar> :set rnu <CR> 
nnoremap <C-c> :%y+<CR>
nnoremap <C-F> :!autopep8 --in-place --aggressive --aggressive %
hi DiffText   cterm=none ctermfg=Black ctermbg=Red gui=none guifg=Black guibg=Red
hi DiffChange cterm=none ctermfg=Black ctermbg=LightMagenta gui=none guifg=Black guibg=LightMagenta
