set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin() "Plugins go between begin and end
Plugin 'VundleVim/Vundle.vim'
Plugin 'reedes/vim-pencil'
call vundle#end()
filetype plugin indent on
syntax on
set rnu
set nu
set clipboard+=unnamedplus
set hidden
set tabstop=4
set shiftwidth=4
set expandtab
set nowrap
so ~/.pythonvimrc
