import os
import time
os.system("cp ~/.config/i3/config ~/git/dotfiles/graveyard/machine/i3config")
os.system("cp ~/git/dotfiles/i3wm/config ~/.config/i3/config ")
print("pulling ~/.config/i3.config....")
time.sleep(.25)
os.system("cp ~/.vimrc ~/git/dotfiles/graveyard/machine/vimrc")
os.system("cp ~/git/dotfiles/vim/vimrc ~/.vimrc ")
print("pulling ~/.vimrc...")
time.sleep(.25)
os.system("cp ~/.pythonvimrc ~/git/dotfiles/graveyard/machine/pythonvimrc")
os.system("cp ~/git/dotfiles/vim/pythonvimrc ~/.pythonvimrc ")
print("pulling ~/.pythonvimrc...")
time.sleep(.25)
os.system("cp ~/.profile ~/git/dotfiles/graveyard/machine/profile")
os.system("cp ~/git/dotfiles/profile/profile ~/.profile")
print("pulling ~/.profile...")
time.sleep(.25)
os.system("cp ~/.bashrc ~/git/dotfiles/graveyard/machine/bashrc")
os.system("cp ~/git/dotfiles/bashrc/bashrc ~/.bashrc")
print("pulling ~/.bashrc...")
time.sleep(.25)
os.system("cp ~/.tmux.conf ~/git/dotfiles/graveyard/machine/tmux.conf")
os.system("cp ~/git/dotfiles/tmux/tmux.conf ~/.tmux.conf")
print("pulling ~/.tmux.conf...")
time.sleep(.25)
print("Done")


