#!/bin/bash
cp -r ~/git/dotfiles/vim/* ~/git/dotfiles/graveyard/repo/
cp ~/.vimrc ~/git/dotfiles/vim/vimrc
cp ~/.pythonvimrc ~/git/dotfiles/vim/pythonvimrc
cp -r ~/.vim/pack/ ~/git/dotfiles/vim/pack/
echo "Copied vim settings to repo!"
