#!/bin/bash
cp -r ~/git/dotfiles/vim/* ~/git/dotfiles/graveyard/repo/
cp ~/.config/nvim/init.vim ~/git/dotfiles/vim/init.vim
cp ~/.vimrc ~/git/dotfiles/vim/vimrc
cp -r ~/.vim/pack/ ~/git/dotfiles/vim/pack/
echo "Copied vim settings to repo!"
